using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedCalculationUnit(typeof(global::AgenaTrader.Custom.Bollinger), typeof(global::AgenaTrader.Custom.RSI), typeof(AgenaTrader.UserCode.ReversalLong_GreenBar), typeof(AgenaTrader.UserCode.ReversalLong_RedBar))]
	[ScanTypeAttribute(ScanType.Long)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("BollingerRSI")]
	[Description("Signal when oversold RSI situtation combined with Prices outside of BollingerBands")]
	public class BB_RSI_Long : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Long;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.FromArgb(255, 255, 255, 0);
			ArrowSize = 0.5;
			TextColor = null;
			ScanColor = Color.Yellow;
			BarHighlightColor = Color.Yellow;
		}

		protected override void OnCalculate()
		{
			LastOutput = MultiBars.GetBarsItem(TimeFrame).Low[0] <= LeadIndicator.Bollinger(MultiBars.GetBarsItem(TimeFrame).Close, 2, 20).Lower[0]
				&& LeadIndicator.RSI(MultiBars.GetBarsItem(TimeFrame).Close, 14, 3).Default[0] < 30
				&& (Math.Abs(LeadIndicator.GetCondition("ReversalLong_GreenBar")[0] - 1) <= Double.Epsilon
				|| Math.Abs(LeadIndicator.GetCondition("ReversalLong_RedBar")[0] - 1) <= Double.Epsilon);
		}
	}
}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manually
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="true" ScanType="Long" IsEntry="true" IsStop="false" IsTarget="false" Category="BollingerRSI" Description="Signal when oversold RSI situtation combined with Prices outside of BollingerBands" ArrowColor="255, 255, 0" TextColor="" ScanColor="Yellow" BarHighlightColor="Yellow">
  <Lexems xsi:type="ScanLexemSerie" Type="Low">
    <TimeFrame>0 Min</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="LessEqual" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="Bollinger" Type="Indicator" FullTypeName="AgenaTrader.Custom.Bollinger">
      <Params>
        <TAParam Name="NumStdDev" IsProperty="true">
          <Value xsi:type="xsd:double">2</Value>
        </TAParam>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Upper band" PlotColor="Gray" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Middle band" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower band" PlotColor="Gray" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">Bollinger(Close, 2, 20)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Default" IsFloatPoint="true" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="RSI" Type="Indicator" FullTypeName="AgenaTrader.Custom.RSI">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">14</Value>
        </TAParam>
        <TAParam Name="Smooth" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="RSI" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Avg" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">RSI(Close, 14, 3)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="30" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemOpenBracket" />
  <Lexems xsi:type="ScanLexemScan">
    <BarsAgo>0</BarsAgo>
    <XmlScan Name="ReversalLong_GreenBar" Type="Scann" FullTypeName="AgenaTrader.UserCode.ReversalLong_GreenBar">
      <Params>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">ReversalLong_GreenBar</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlScan>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="Or" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemScan">
    <BarsAgo>0</BarsAgo>
    <XmlScan Name="ReversalLong_RedBar" Type="Scann" FullTypeName="AgenaTrader.UserCode.ReversalLong_RedBar">
      <Params>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">ReversalLong_RedBar</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlScan>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCloseBracket" />
  <Lexems xsi:type="ScanLexemEol" />
  <CalculateOnBarClose xsi:nil="true" />
  <ArrowSize>0.5</ArrowSize>
</ScanWizartState>
*/
#endregion
