using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedCalculationUnit(typeof(global::AgenaTrader.Custom.PivotPoints))]
	[ScanTypeAttribute(ScanType.Short)]
	[IsEntryAttribute(false)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("Pivots")]
	[Description("Price crosses below Pivot Point")]
	public class CrossBelowPivotPoint : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Short;

			IsEntry = false;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.Red;
			ArrowSize = 0.5;
			TextColor = null;
			ScanColor = null;
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = CrossBelow(MultiBars.GetBarsItem(TimeFrame).Close, LeadIndicator.PivotPoints(MultiBars.GetBarsItem(TimeFrame).Close, global::AgenaTrader.Custom.PivotPointsMode.Floor, global::AgenaTrader.Custom.PivotPointsRange.DayOnIntraday).PP, 1);
		}
	}
}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manually
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="false" ScanType="Short" IsEntry="false" IsStop="false" IsTarget="false" Category="Pivots" Description="Price crosses below Pivot Point" ArrowColor="Red" TextColor="" ScanColor="" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemSerie" Type="Close">
    <TimeFrame>0 Min</TimeFrame>
    <BarsAgo xsi:nil="true" />
  </Lexems>
  <Lexems xsi:type="ScanLexemCrossOperation" Operation="CrossBelow" Period="1" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="PP" IsFloatPoint="true" RoundToTickSize="false">
    <BarsAgo xsi:nil="true" />
    <XmlIndicator Name="PivotPoints" Type="Indicator" FullTypeName="AgenaTrader.Custom.PivotPoints">
      <Params>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Mode" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="Range" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="LineWidth" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="ShowPrices" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="PeriodsBack" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="R_ColorSerialize" IsProperty="true">
          <Value xsi:type="xsd:string">RoyalBlue</Value>
        </TAParam>
        <TAParam Name="PP_ColorSerialize" IsProperty="true">
          <Value xsi:type="xsd:string">Black</Value>
        </TAParam>
        <TAParam Name="S_ColorSerialize" IsProperty="true">
          <Value xsi:type="xsd:string">LightSalmon</Value>
        </TAParam>
        <TAParam Name="FontSerialize" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="R3" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="R2" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="R1" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="PP" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="S1" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="S2" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="S3" PlotColor="0, 0, 0, 0" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">PivotPoints(Close, Floor, Day)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <CalculateOnBarClose xsi:nil="true" />
  <ArrowSize>0.5</ArrowSize>
</ScanWizartState>
*/
#endregion
