using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedScans(typeof(AgenaTrader.UserCode.Filter_Long_1D))]
	[ScanTypeAttribute(ScanType.Long)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("")]
	[Description("Entry am 1. P2 Limit")]
	public class P2_Limit : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Long;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.FromArgb(255, 0, 102, 0);
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = Math.Abs(LeadIndicator.GetCondition("Filter_Long_1D")[0] - 1) <= Double.Epsilon
				&& LeadIndicator.P123Pro(MultiBars.GetBarsItem(TimeFrame).Close, 2, 0, global::AgenaTrader.Custom.P123ProInfo.None, global::AgenaTrader.Custom.P123ProValidationMethod.Correction, 0, 0, 0, false)[0] > MultiBars.GetBarsItem(TimeFrame).Low[0];
		}
	}

}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manualy
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="false" ScanType="Long" IsEntry="true" IsStop="false" IsTarget="false" Category="" Description="Entry am 1. P2 Limit" ArrowColor="0, 102, 0" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemScan">
    <BarsAgo>0</BarsAgo>
    <XmlScan Name="Filter_Long_1D" Type="Scann" FullTypeName="AgenaTrader.UserCode.Filter_Long_1D">
      <Params>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">Filter_Long_1D</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlScan>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="P123Pro" Type="Indicator" FullTypeName="AgenaTrader.Custom.P123Pro">
      <Params>
        <TAParam Name="ShowT0_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_P2Breakout" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_P2Breakout" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT2_P2Breakout" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_P2Breakout" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="BreakageP2" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="ExtInfo" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="P2ValidationMethod" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="P2Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3BreakageDistance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="BreakTheTrendByCS" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="P123ProStartDt" IsProperty="true">
          <Value xsi:type="xsd:dateTime">0001-01-01T00:00:00</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Purple</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor0" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="ShowP3Lines0" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Width0" IsProperty="true">
          <Value xsi:type="xsd:int">4</Value>
        </TAParam>
        <TAParam Name="DashStyle0" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="FontSize0" IsProperty="true">
          <Value xsi:type="xsd:int">14</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Navy</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor1" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="ShowP3Lines1" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Width1" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="DashStyle1" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="FontSize1" IsProperty="true">
          <Value xsi:type="xsd:int">12</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor2" IsProperty="true">
          <Value xsi:type="xsd:string">DarkGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor2" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor2" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="ShowP3Lines2" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Width2" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="DashStyle2" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="FontSize2" IsProperty="true">
          <Value xsi:type="xsd:int">10</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor3" IsProperty="true">
          <Value xsi:type="xsd:string">IndianRed</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor3" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor3" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="ShowP3Lines3" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Width3" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="DashStyle3" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="FontSize3" IsProperty="true">
          <Value xsi:type="xsd:int">8</Value>
        </TAParam>
        <TAParam Name="DrawP2P1Line" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2P1LineColor" IsProperty="true">
          <Value xsi:type="xsd:string">Blue</Value>
        </TAParam>
        <TAParam Name="ShowP2BreakoutArrows" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2BreakoutColorUp" IsProperty="true">
          <Value xsi:type="xsd:string">SkyBlue</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2BreakoutColorDown" IsProperty="true">
          <Value xsi:type="xsd:string">White</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <OutputDescriptor Name="DummyPlot" PlotColor="Blue" Width="1" OutputSerieDrawStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">P123Pro</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemSerie" Type="Low">
    <TimeFrame>0 Min</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <CalculateOnClosedBar xsi:nil="true" />
</ScanWizartState>
*/
#endregion