using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedScans(typeof(AgenaTrader.UserCode.ReversalShort_GreenBar), typeof(AgenaTrader.UserCode.ReversalShort_RedBar))]
	[ScanTypeAttribute(ScanType.Short)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("ReversalBars")]
	[Description("Scans for a ReversalShort at the SMA200 after 3 rising bars")]
	public class ReversalShortatSMA200_3RisingBars : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Short;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.FromArgb(255, 255, 0, 0);
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = (Math.Abs(LeadIndicator.GetCondition("ReversalShort_GreenBar")[0] - 1) <= Double.Epsilon
				|| Math.Abs(LeadIndicator.GetCondition("ReversalShort_RedBar")[0] - 1) <= Double.Epsilon)
				&& (Math.Abs(LeadIndicator.NBarsUp(MultiBars.GetBarsItem(TimeFrame).Close, 3, true, false, false)[0] - 1) <= Double.Epsilon
				|| Math.Abs(LeadIndicator.NBarsUp(MultiBars.GetBarsItem(TimeFrame).Close, 3, false, false, true)[0] - 1) <= Double.Epsilon
				|| Math.Abs(LeadIndicator.NBarsUp(MultiBars.GetBarsItem(TimeFrame).Close, 3, false, true, false)[0] - 1) <= Double.Epsilon)
				&& MultiBars.GetBarsItem(TimeFrame).Close[0] < LeadIndicator.SMA(MultiBars.GetBarsItem(TimeFrame).Close, 200)[0]
				&& ((LeadIndicator.SMA(MultiBars.GetBarsItem(TimeFrame).Close, 200)[0]-MultiBars.GetBarsItem(TimeFrame).Close[0])) <= ((LeadIndicator.ATR(MultiBars.GetBarsItem(TimeFrame).Close, 14)[0]*1.5));
		}
	}

}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manualy
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="true" ScanType="Short" IsEntry="true" IsStop="false" IsTarget="false" Category="ReversalBars" Description="Scans for a ReversalShort at the SMA200 after 3 rising bars" ArrowColor="255, 0, 0" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemOpenBracket" />
  <Lexems xsi:type="ScanLexemScan">
    <BarsAgo>0</BarsAgo>
    <XmlScan Name="ReversalShort_GreenBar" Type="Scann" FullTypeName="AgenaTrader.UserCode.ReversalShort_GreenBar">
      <Params>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">ReversalShort_GreenBar</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlScan>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="Or" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemScan">
    <BarsAgo>0</BarsAgo>
    <XmlScan Name="ReversalShort_RedBar" Type="Scann" FullTypeName="AgenaTrader.UserCode.ReversalShort_RedBar">
      <Params>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">0 Min</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">ReversalShort_RedBar</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlScan>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCloseBracket" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemOpenBracket" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="NBarsUp" Type="Indicator" FullTypeName="AgenaTrader.Custom.NBarsUp">
      <Params>
        <TAParam Name="BarCount" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="BarUp" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="HigherHigh" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="HigherLow" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <OutputDescriptor Name="NBarsUp" PlotColor="50, 205, 50" Width="2" OutputSerieDrawStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">NBarsUp(Close, 3, True, True, True)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="Or" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="NBarsUp" Type="Indicator" FullTypeName="AgenaTrader.Custom.NBarsUp">
      <Params>
        <TAParam Name="BarCount" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="BarUp" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="HigherHigh" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="HigherLow" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <OutputDescriptor Name="NBarsUp" PlotColor="50, 205, 50" Width="2" OutputSerieDrawStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">NBarsUp(Close, 3, True, True, True)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="Or" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="NBarsUp" Type="Indicator" FullTypeName="AgenaTrader.Custom.NBarsUp">
      <Params>
        <TAParam Name="BarCount" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="BarUp" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="HigherHigh" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="HigherLow" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <OutputDescriptor Name="NBarsUp" PlotColor="50, 205, 50" Width="2" OutputSerieDrawStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">NBarsUp(Close, 3, True, True, True)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCloseBracket" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemSerie" Type="Close">
    <TimeFrame>0 Min</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="SMA" Type="Indicator" FullTypeName="AgenaTrader.Custom.SMA">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">200</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <OutputDescriptor Name="SMA" PlotColor="0, 0, 255" Width="1" OutputSerieDrawStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">SMA(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
      <BarsAgo>0</BarsAgo>
      <XmlIndicator Name="SMA" Type="Indicator" FullTypeName="AgenaTrader.Custom.SMA">
        <Params>
          <TAParam Name="Period" IsProperty="true">
            <Value xsi:type="xsd:int">200</Value>
          </TAParam>
          <TAParam Name="XmlInstrument" IsProperty="true" />
          <TAParam Name="TimeFrame" IsProperty="true" />
          <TAParam Name="VisibleIndicatorValues" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Overlay" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="DisplayInDataBox" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="PaintPriceMarkers" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="VerticalGridLines" IsProperty="true" />
          <TAParam Name="DrawOnPricePanel" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="Displacement" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Panel" IsProperty="true">
            <Value xsi:type="xsd:string">Same as input series</Value>
          </TAParam>
          <TAParam Name="IsPanelCustom" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="XmlPlots" IsProperty="true">
            <Value xsi:type="ArrayOfPlot">
              <OutputDescriptor Name="SMA" PlotColor="0, 0, 255" Width="1" OutputSerieDrawStyle="Line" PenStyle="Solid" />
            </Value>
          </TAParam>
          <TAParam Name="XmlLines" IsProperty="true">
            <Value xsi:type="ArrayOfLine" />
          </TAParam>
          <TAParam Name="FixedInputParameters" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">0</Value>
          </TAParam>
          <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
          <TAParam Name="AutoScale" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="InputPriceType" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">3</Value>
          </TAParam>
          <TAParam Name="CustomInput" IsProperty="true" />
          <TAParam Name="CalculateOnBarClose" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="BarsRequired" IsProperty="true">
            <Value xsi:type="xsd:int">20</Value>
          </TAParam>
          <TAParam Name="Caption" IsProperty="true">
            <Value xsi:type="xsd:string">SMA(Close, 14)</Value>
          </TAParam>
          <TAParam Name="Tags" IsProperty="true" />
        </Params>
      </XmlIndicator>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Minus" />
    <Lexems xsi:type="ScanLexemSerie" Type="Close">
      <TimeFrame>0 Min</TimeFrame>
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>false</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="LessEqual" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
      <BarsAgo>0</BarsAgo>
      <XmlIndicator Name="ATR" Type="Indicator" FullTypeName="AgenaTrader.Custom.ATR">
        <Params>
          <TAParam Name="Period" IsProperty="true">
            <Value xsi:type="xsd:int">14</Value>
          </TAParam>
          <TAParam Name="XmlInstrument" IsProperty="true" />
          <TAParam Name="TimeFrame" IsProperty="true" />
          <TAParam Name="VisibleIndicatorValues" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Overlay" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="DisplayInDataBox" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="PaintPriceMarkers" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="VerticalGridLines" IsProperty="true" />
          <TAParam Name="DrawOnPricePanel" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="Displacement" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Panel" IsProperty="true">
            <Value xsi:type="xsd:string">New Panel</Value>
          </TAParam>
          <TAParam Name="IsPanelCustom" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="XmlPlots" IsProperty="true">
            <Value xsi:type="ArrayOfPlot">
              <OutputDescriptor Name="ATR" PlotColor="0, 128, 0" Width="1" OutputSerieDrawStyle="Line" PenStyle="Solid" />
            </Value>
          </TAParam>
          <TAParam Name="XmlLines" IsProperty="true">
            <Value xsi:type="ArrayOfLine" />
          </TAParam>
          <TAParam Name="FixedInputParameters" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">0</Value>
          </TAParam>
          <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
          <TAParam Name="AutoScale" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="InputPriceType" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">3</Value>
          </TAParam>
          <TAParam Name="CustomInput" IsProperty="true" />
          <TAParam Name="CalculateOnBarClose" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="BarsRequired" IsProperty="true">
            <Value xsi:type="xsd:int">20</Value>
          </TAParam>
          <TAParam Name="Caption" IsProperty="true">
            <Value xsi:type="xsd:string">ATR(Close, 14)</Value>
          </TAParam>
          <TAParam Name="Tags" IsProperty="true" />
        </Params>
      </XmlIndicator>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Multiple" />
    <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1.5" CharValue="0" />
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>false</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemEol" />
  <CalculateOnBarClose xsi:nil="true" />
</ScanWizartState>
*/
#endregion