using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedCalculationUnit(typeof(global::AgenaTrader.Custom.RSI))]
	[ScanTypeAttribute(ScanType.Short)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("RSI")]
	[Description("Scans for overbougth situations with RSI")]
	public class RSI_overbought : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Short;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.Red;
			ArrowSize = 0.5;
			TextColor = null;
			ScanColor = null;
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = LeadIndicator.RSI(MultiBars.GetBarsItem(TimeFrame).Close, 14, 3).Default[0] > 70;
		}
	}
}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manually
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="false" ScanType="Short" IsEntry="true" IsStop="false" IsTarget="false" Category="RSI" Description="Scans for overbougth situations with RSI" ArrowColor="Red" TextColor="" ScanColor="" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemIndicator" Serie="Default" IsFloatPoint="true" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="RSI" Type="Indicator" FullTypeName="AgenaTrader.Custom.RSI">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">14</Value>
        </TAParam>
        <TAParam Name="Smooth" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="RSI" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Average" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine">
            <LevelLine Name="Lower" XmlColor="Violet" Value="30" Width="1" DashStyle="Solid" />
            <LevelLine Name="Upper" XmlColor="LimeGreen" Value="70" Width="1" DashStyle="Solid" />
            <LevelLine Name="3rdLine" XmlColor="Brown" Value="NaN" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">RSI(Close, 14, 3)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="70" CharValue="0" />
  <CalculateOnBarClose xsi:nil="true" />
  <ArrowSize>0.5</ArrowSize>
</ScanWizartState>
*/
#endregion
