using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[UsedCalculationUnit(typeof(global::AgenaTrader.Custom.MarketPhasesPro), typeof(global::AgenaTrader.Custom.P123Adv))]
	[ScanTypeAttribute(ScanType.Long)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("")]
	[Description("Trendwechsel")]
	public class Trendwechsel : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Long;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.LawnGreen;
			ArrowSize = 1;
			TextColor = null;
			ScanColor = null;
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = LeadIndicator.MarketPhasesPro(MultiBars.GetBarsItem(TimeFrame).Close, 1, 0.2, 0.5, global::AgenaTrader.Custom.P123ProValidationMethod.Correction, 0, 0, 0, false)[0] > 0
				&& LeadIndicator.P123Adv(MultiBars.GetBarsItem(TimeFrame).Close, 2).IsP21[0] == true
				&& LeadIndicator.P123Adv(MultiBars.GetBarsItem(TimeFrame).Close, 2).IsTrendValid[0] == true
				&& LeadIndicator.P123Adv(MultiBars.GetBarsItem(TimeFrame).Close, 2).TrendDirection[0] > 1
				&& LeadIndicator.P123Adv(MultiBars.GetBarsItem(TimeFrame).Close, 2).TrendAge[0] < 2;
		}
	}
}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manually
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="false" ScanType="Long" IsEntry="true" IsStop="false" IsTarget="false" Category="" Description="Trendwechsel" ArrowColor="LawnGreen" TextColor="" ScanColor="" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="MarketPhasesPro" Type="Indicator" FullTypeName="AgenaTrader.Custom.MarketPhasesPro">
      <Params>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="Phase4Level" IsProperty="true">
          <Value xsi:type="xsd:double">0.2</Value>
        </TAParam>
        <TAParam Name="Phase5Level" IsProperty="true">
          <Value xsi:type="xsd:double">0.5</Value>
        </TAParam>
        <TAParam Name="P2ValidationMethod" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="P2Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3BreakageDistance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="BreakTheTrendByCS" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Location" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Chart Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="MarketPhase" PlotColor="DarkOrange" Width="4" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">200</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">Market Phases Pro</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="IsP21" IsFloatPoint="false" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="P123Adv" Type="Indicator" FullTypeName="AgenaTrader.Custom.P123Adv">
      <Params>
        <TAParam Name="ShowT0_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Purple</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor0" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width0" IsProperty="true">
          <Value xsi:type="xsd:int">4</Value>
        </TAParam>
        <TAParam Name="DashStyle0" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Navy</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor1" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width1" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="DashStyle1" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor2" IsProperty="true">
          <Value xsi:type="xsd:string">DarkGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor2" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor2" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width2" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="DashStyle2" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor3" IsProperty="true">
          <Value xsi:type="xsd:string">IndianRed</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor3" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor3" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width3" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="DashStyle3" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="DrawP2P1Line" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2P1LineColor" IsProperty="true">
          <Value xsi:type="xsd:string">Blue</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Chart Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="DummyPlot" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">P123Adv</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Boolean" BoolValue="true" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="IsTrendValid" IsFloatPoint="false" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="P123Adv" Type="Indicator" FullTypeName="AgenaTrader.Custom.P123Adv">
      <Params>
        <TAParam Name="ShowT0_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Purple</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor0" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width0" IsProperty="true">
          <Value xsi:type="xsd:int">4</Value>
        </TAParam>
        <TAParam Name="DashStyle0" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Navy</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor1" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width1" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="DashStyle1" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor2" IsProperty="true">
          <Value xsi:type="xsd:string">DarkGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor2" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor2" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width2" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="DashStyle2" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor3" IsProperty="true">
          <Value xsi:type="xsd:string">IndianRed</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor3" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor3" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width3" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="DashStyle3" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="DrawP2P1Line" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2P1LineColor" IsProperty="true">
          <Value xsi:type="xsd:string">Blue</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Chart Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="DummyPlot" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">P123Adv</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Boolean" BoolValue="true" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="TrendDirection" IsFloatPoint="false" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="P123Adv" Type="Indicator" FullTypeName="AgenaTrader.Custom.P123Adv">
      <Params>
        <TAParam Name="ShowT0_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Purple</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor0" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width0" IsProperty="true">
          <Value xsi:type="xsd:int">4</Value>
        </TAParam>
        <TAParam Name="DashStyle0" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Navy</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor1" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width1" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="DashStyle1" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor2" IsProperty="true">
          <Value xsi:type="xsd:string">DarkGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor2" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor2" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width2" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="DashStyle2" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor3" IsProperty="true">
          <Value xsi:type="xsd:string">IndianRed</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor3" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor3" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width3" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="DashStyle3" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="DrawP2P1Line" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2P1LineColor" IsProperty="true">
          <Value xsi:type="xsd:string">Blue</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Chart Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="DummyPlot" PlotColor="0, 0, 255" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">P123Adv</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="TrendAge" IsFloatPoint="false" RoundToTickSize="false">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="P123Adv" Type="Indicator" FullTypeName="AgenaTrader.Custom.P123Adv">
      <Params>
        <TAParam Name="ShowT0_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_123" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT0_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT1_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="ShowT2_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ShowT3_Lines" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Purple</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor0" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor0" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width0" IsProperty="true">
          <Value xsi:type="xsd:int">4</Value>
        </TAParam>
        <TAParam Name="DashStyle0" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Navy</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor1" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor1" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width1" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="DashStyle1" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor2" IsProperty="true">
          <Value xsi:type="xsd:string">DarkGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor2" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor2" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width2" IsProperty="true">
          <Value xsi:type="xsd:int">2</Value>
        </TAParam>
        <TAParam Name="DashStyle2" IsProperty="true">
          <Value xsi:type="DashStyle">Dot</Value>
        </TAParam>
        <TAParam Name="ColorSerializeTextColor3" IsProperty="true">
          <Value xsi:type="xsd:string">IndianRed</Value>
        </TAParam>
        <TAParam Name="ColorSerializeUpColor3" IsProperty="true">
          <Value xsi:type="xsd:string">LimeGreen</Value>
        </TAParam>
        <TAParam Name="ColorSerializeDownColor3" IsProperty="true">
          <Value xsi:type="xsd:string">Red</Value>
        </TAParam>
        <TAParam Name="Width3" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="DashStyle3" IsProperty="true">
          <Value xsi:type="DashStyle">Solid</Value>
        </TAParam>
        <TAParam Name="DrawP2P1Line" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="ColorSerializeP2P1LineColor" IsProperty="true">
          <Value xsi:type="xsd:string">Blue</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true" />
        <TAParam Name="ChartVisibleValuesCount" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="IsOverlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="IsShowInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="IsShowChartVerticalGrid" IsProperty="true" />
        <TAParam Name="IsAddDrawingsToPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Chart Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="DummyPlot" PlotColor="0, 0, 255" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLevelLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="OutputsDisplayStyle" IsProperty="true" />
        <TAParam Name="IsAutoAdjustableScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnClosedBar" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="CalculationUpdatesTimeFrame" IsProperty="true" />
        <TAParam Name="RequiredBarsCount" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">P123Adv</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="2" CharValue="0" />
  <CalculateOnBarClose xsi:nil="true" />
  <ArrowSize>1</ArrowSize>
</ScanWizartState>
*/
#endregion
