using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[ScanTypeAttribute(ScanType.Short)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("")]
	[Description("")]
	public class TurtleShort : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Short;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.Red;
			BarHighlightColor = null;

			CalculateOnClosedBar = false;
		}

		protected override void OnCalculate()
		{
			LastOutput = MultiBars.GetBarsItem(TimeFrame).Low[0] < LeadIndicator.DonchianChannel(MultiBars.GetBarsItem(TimeFrame).Close, 20).Lower[1]
				&& Math.Abs(LeadIndicator.DonchianChannel(MultiBars.GetBarsItem(TimeFrame).Close, 20).Lower[1] - LeadIndicator.DonchianChannel(MultiBars.GetBarsItem(TimeFrame).Close, 20).Lower[3]) <= Double.Epsilon
				&& Math.Abs(LeadIndicator.DonchianChannel(MultiBars.GetBarsItem(TimeFrame).Close, 20).Lower[3] - LeadIndicator.DonchianChannel(MultiBars.GetBarsItem(TimeFrame).Close, 20).Lower[5]) <= Double.Epsilon
				&& LeadIndicator.RSI(MultiBars.GetBarsItem(TimeFrame).Close, 14, 3).Default[0] < 50
				&& LeadIndicator.MACD(MultiBars.GetBarsItem(TimeFrame).Close, 12, 26, 9).Default[0] < LeadIndicator.MACD(MultiBars.GetBarsItem(TimeFrame).Close, 12, 26, 9).Avg[0];
		}
	}

	#region AgenaTrader Automaticaly Generated Code. Do not change it manualy

	public partial class UserScan
	{
		public TurtleShort TurtleShort()
		{
			return GetCondition<TurtleShort>();
		}

		public TurtleShort TurtleShort(IDataSeries input)
		{
			return GetCondition<TurtleShort>(input);
		}
	}

	#endregion
}
#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manualy
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Advanved="false" ScanType="Short" IsEntry="true" IsStop="false" IsTarget="false" Category="" Description="" ArrowColor="Red" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemSerie" Type="Low">
    <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true">
    <BarsAgo>1</BarsAgo>
    <XmlIndicator Name="DonchianChannel" Type="Indicator" FullTypeName="AgenaTrader.Custom.DonchianChannel">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Mean" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Upper" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">DonchianChannel(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true">
    <BarsAgo>1</BarsAgo>
    <XmlIndicator Name="DonchianChannel" Type="Indicator" FullTypeName="AgenaTrader.Custom.DonchianChannel">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Mean" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Upper" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">DonchianChannel(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true">
    <BarsAgo>3</BarsAgo>
    <XmlIndicator Name="DonchianChannel" Type="Indicator" FullTypeName="AgenaTrader.Custom.DonchianChannel">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Mean" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Upper" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">DonchianChannel(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true">
    <BarsAgo>3</BarsAgo>
    <XmlIndicator Name="DonchianChannel" Type="Indicator" FullTypeName="AgenaTrader.Custom.DonchianChannel">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Mean" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Upper" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">DonchianChannel(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Lower" IsFloatPoint="true">
    <BarsAgo>5</BarsAgo>
    <XmlIndicator Name="DonchianChannel" Type="Indicator" FullTypeName="AgenaTrader.Custom.DonchianChannel">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Transparency" IsProperty="true">
          <Value xsi:type="xsd:decimal">25</Value>
        </TAParam>
        <TAParam Name="XmlLowerMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperMiddleBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlUpperLowerBandsColor" IsProperty="true">
          <Value xsi:type="xsd:string" />
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Mean" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Upper" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Lower" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">DonchianChannel(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Default" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="RSI" Type="Indicator" FullTypeName="AgenaTrader.Custom.RSI">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">14</Value>
        </TAParam>
        <TAParam Name="Smooth" IsProperty="true">
          <Value xsi:type="xsd:int">3</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="RSI" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Avg" PlotColor="OrangeRed" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Lower" XmlColor="DarkViolet" Value="30" Width="1" DashStyle="Solid" />
            <Line Name="Upper" XmlColor="YellowGreen" Value="70" Width="1" DashStyle="Solid" />
            <Line Name="3rdLine" XmlColor="Brown" Value="NaN" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">RSI(Close, 14, 3)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="50" BoolValue="false" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Default" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="MACD" Type="Indicator" FullTypeName="AgenaTrader.Custom.MACD">
      <Params>
        <TAParam Name="Fast" IsProperty="true">
          <Value xsi:type="xsd:int">12</Value>
        </TAParam>
        <TAParam Name="Slow" IsProperty="true">
          <Value xsi:type="xsd:int">26</Value>
        </TAParam>
        <TAParam Name="Smooth" IsProperty="true">
          <Value xsi:type="xsd:int">9</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Macd" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Avg" PlotColor="DarkViolet" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Diff" PlotColor="Navy" Width="2" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Zero line" XmlColor="DarkGray" Value="0" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">MACD(Close, 12, 26, 9)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="Avg" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="MACD" Type="Indicator" FullTypeName="AgenaTrader.Custom.MACD">
      <Params>
        <TAParam Name="Fast" IsProperty="true">
          <Value xsi:type="xsd:int">12</Value>
        </TAParam>
        <TAParam Name="Slow" IsProperty="true">
          <Value xsi:type="xsd:int">26</Value>
        </TAParam>
        <TAParam Name="Smooth" IsProperty="true">
          <Value xsi:type="xsd:int">9</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="TimeFrame" Periodicity="Minute" PeriodicityValue="0" />
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Macd" PlotColor="Green" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Avg" PlotColor="DarkViolet" Width="1" PlotStyle="Line" PenStyle="Solid" />
            <Plot Name="Diff" PlotColor="Navy" Width="2" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Zero line" XmlColor="DarkGray" Value="0" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">MACD(Close, 12, 26, 9)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <CalculateOnClosedBar>false</CalculateOnClosedBar>
</ScanWizartState>
*/
#endregion
