using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[ScanTypeAttribute(ScanType.Long)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("")]
	[Description("")]
	public class UKSRotLong : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Long;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.LawnGreen;
			BarHighlightColor = null;
		}

		protected override void OnCalculate()
		{
			LastOutput = MultiBars.GetBarsItem(TimeFrame).Open[0] > MultiBars.GetBarsItem(TimeFrame).Close[0]
				&& ((MultiBars.GetBarsItem(TimeFrame).Close[0]-MultiBars.GetBarsItem(TimeFrame).Low[0])) > ((MultiBars.GetBarsItem(TimeFrame).High[0]-MultiBars.GetBarsItem(TimeFrame).Close[0]))
				&& ((MultiBars.GetBarsItem(TimeFrame).High[0]-MultiBars.GetBarsItem(TimeFrame).Close[0])) < (((MultiBars.GetBarsItem(TimeFrame).High[0]-MultiBars.GetBarsItem(TimeFrame).Low[0])*(0.45*1)));
		}
	}

}
#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manualy
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Advanved="false" ScanType="Long" IsEntry="true" IsStop="false" IsTarget="false" Category="" Description="" ArrowColor="LawnGreen" BarHighlightColor="">
  <Lexems xsi:type="ScanLexemSerie" Type="Open">
    <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemSerie" Type="Close">
    <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemSerie" Type="Close">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Minus" />
    <Lexems xsi:type="ScanLexemSerie" Type="Low">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>false</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemSerie" Type="High">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Minus" />
    <Lexems xsi:type="ScanLexemSerie" Type="Close">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>false</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemSerie" Type="High">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Minus" />
    <Lexems xsi:type="ScanLexemSerie" Type="Close">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>false</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemSerie" Type="High">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Minus" />
    <Lexems xsi:type="ScanLexemSerie" Type="Low">
      <TimeFrame Periodicity="Minute" PeriodicityValue="0" />
      <BarsAgo>0</BarsAgo>
    </Lexems>
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Multiple" />
    <Lexems xsi:type="ScanLexemEol" />
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="0.45" CharValue="0" />
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Multiple" />
    <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="1" CharValue="0" />
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <Lexems xsi:type="ScanLexemEol" />
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>true</IsAdvanced>
  </Lexems>
  <CalculateOnClosedBar xsi:nil="true" />
</ScanWizartState>
*/
#endregion