using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Xml;
using System.Xml.Serialization;
using global::AgenaTrader.API;
using global::AgenaTrader.Custom;
using global::AgenaTrader.Plugins;

namespace AgenaTrader.UserCode
{
	[TimeFrameRequirements("1 Day")]
	[ScanTypeAttribute(ScanType.Long)]
	[IsEntryAttribute(true)]
	[IsStopAttribute(false)]
	[IsTargetAttribute(false)]
	[Category("")]
	[Description("Volumenspitze und MFI < 35 MP T01> 0")]
	public class Vol_Peek_MFI : UserScan
	{
		protected override void OnInit()
		{
			ScanType = ScanType.Long;

			IsEntry = true;
			IsStop = false;
			IsTarget = false;

			ArrowColor = Color.FromArgb(255, 0, 255, 204);
			BarHighlightColor = Color.FromArgb(255, 0, 255, 204);
		}

		private static readonly ITimeFrame GenTF_1 = CoreInstanse.Current.TimeFrameFactory.Create(global::AgenaTrader.Plugins.DatafeedHistoryPeriodicity.Day, new global::AgenaTrader.Plugins.TimeFrames.RegularTimeFrameParameters(1));

		protected override void OnCalculate()
		{
			LastOutput = (LeadIndicator.VOL(MultiBars.GetBarsItem(GenTF_1).Close)[0] > ((2*LeadIndicator.SMA(MultiBars.GetBarsItem(GenTF_1).Volume, 14)[0]))
				|| LeadIndicator.VOL(MultiBars.GetBarsItem(GenTF_1).Close)[1] > ((LeadIndicator.SMA(MultiBars.GetBarsItem(GenTF_1).Volume, 14)[0]*2)))
				&& LeadIndicator.MFI(MultiBars.GetBarsItem(GenTF_1).Close, 14)[0] < 35
				&& MultiBars.GetBarsItem(GenTF_1).High[0] > MultiBars.GetBarsItem(GenTF_1).Low[0]
				&& LeadIndicator.MarketPhasesPro(MultiBars.GetBarsItem(GenTF_1).Close, 1, 0.2, 0.5, global::AgenaTrader.Custom.P123ProValidationMethod.Correction, 0, 0, 0, false)[0] > 0
				&& Math.Abs(LeadIndicator.InsideBarsMT(MultiBars.GetBarsItem(GenTF_1).Close, global::AgenaTrader.Custom.InsideBarsMTToleranceUnit.Ticks, 2).IsInsideBar[0] - 0) <= Double.Epsilon
				&& MultiBars.GetBarsItem(GenTF_1).Close[0] > 8;
		}
	}

	#region AgenaTrader Automaticaly Generated Code. Do not change it manualy

	public partial class UserScan
	{
		public Vol_Peek_MFI Vol_Peek_MFI()
		{
			return GetCondition<Vol_Peek_MFI>();
		}

		public Vol_Peek_MFI Vol_Peek_MFI(IDataSeries input)
		{
			return GetCondition<Vol_Peek_MFI>(input);
		}
	}

	#endregion
}

#region XML. Generated by ScanningEscort Tool. Do not change or remove this region manualy
/*
<?xml version="1.0" encoding="utf-16"?>
<ScanWizartState xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Advanved="true" ScanType="Long" IsEntry="true" IsStop="false" IsTarget="false" Category="" Description="Volumenspitze und MFI &lt; 35 MP T01&gt; 0" ArrowColor="0, 255, 204" BarHighlightColor="0, 255, 204">
  <Lexems xsi:type="ScanLexemOpenBracket" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="VOL" Type="Indicator" FullTypeName="AgenaTrader.Custom.VOL">
      <Params>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">1 Day</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Volume" PlotColor="Blue" Width="2" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Zero line" XmlColor="DarkGray" Value="0" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true">
          <Value xsi:type="SuffixedPriceDisplayStyle" />
        </TAParam>
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">VOL(Close)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="2" CharValue="0" />
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Multiple" />
    <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
      <BarsAgo>0</BarsAgo>
      <XmlIndicator Name="SMA" Type="Indicator" FullTypeName="AgenaTrader.Custom.SMA">
        <Params>
          <TAParam Name="Period" IsProperty="true">
            <Value xsi:type="xsd:int">14</Value>
          </TAParam>
          <TAParam Name="XmlInstrument" IsProperty="true" />
          <TAParam Name="TimeFrame" IsProperty="true">
            <Value xsi:type="xsd:string">1 Day</Value>
          </TAParam>
          <TAParam Name="VisibleIndicatorValues" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Overlay" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="DisplayInDataBox" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="PaintPriceMarkers" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="VerticalGridLines" IsProperty="true" />
          <TAParam Name="DrawOnPricePanel" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="Displacement" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Panel" IsProperty="true">
            <Value xsi:type="xsd:string">Same as input series</Value>
          </TAParam>
          <TAParam Name="IsPanelCustom" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="XmlPlots" IsProperty="true">
            <Value xsi:type="ArrayOfPlot">
              <Plot Name="SMA" PlotColor="0, 0, 255" Width="1" PlotStyle="Line" PenStyle="Solid" />
            </Value>
          </TAParam>
          <TAParam Name="XmlLines" IsProperty="true">
            <Value xsi:type="ArrayOfLine" />
          </TAParam>
          <TAParam Name="FixedInputParameters" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">0</Value>
          </TAParam>
          <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
          <TAParam Name="AutoScale" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="InputPriceType" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">4</Value>
          </TAParam>
          <TAParam Name="CustomInput" IsProperty="true" />
          <TAParam Name="CalculateOnBarClose" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="BarsRequired" IsProperty="true">
            <Value xsi:type="xsd:int">20</Value>
          </TAParam>
          <TAParam Name="Caption" IsProperty="true">
            <Value xsi:type="xsd:string">SMA(Close, 14)</Value>
          </TAParam>
          <TAParam Name="Tags" IsProperty="true" />
        </Params>
      </XmlIndicator>
    </Lexems>
    <Lexems xsi:type="ScanLexemEol" />
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>true</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="Or" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>1</BarsAgo>
    <XmlIndicator Name="VOL" Type="Indicator" FullTypeName="AgenaTrader.Custom.VOL">
      <Params>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">1 Day</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="Volume" PlotColor="Blue" Width="2" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Zero line" XmlColor="DarkGray" Value="0" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true">
          <Value xsi:type="SuffixedPriceDisplayStyle" />
        </TAParam>
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">VOL(Close)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemCalculation">
    <Lexems xsi:type="ScanLexemOpenBracket" />
    <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
      <BarsAgo>0</BarsAgo>
      <XmlIndicator Name="SMA" Type="Indicator" FullTypeName="AgenaTrader.Custom.SMA">
        <Params>
          <TAParam Name="Period" IsProperty="true">
            <Value xsi:type="xsd:int">14</Value>
          </TAParam>
          <TAParam Name="XmlInstrument" IsProperty="true" />
          <TAParam Name="TimeFrame" IsProperty="true">
            <Value xsi:type="xsd:string">1 Day</Value>
          </TAParam>
          <TAParam Name="VisibleIndicatorValues" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Overlay" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="DisplayInDataBox" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="PaintPriceMarkers" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="VerticalGridLines" IsProperty="true" />
          <TAParam Name="DrawOnPricePanel" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="Displacement" IsProperty="true">
            <Value xsi:type="xsd:int">0</Value>
          </TAParam>
          <TAParam Name="Panel" IsProperty="true">
            <Value xsi:type="xsd:string">Same as input series</Value>
          </TAParam>
          <TAParam Name="IsPanelCustom" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="XmlPlots" IsProperty="true">
            <Value xsi:type="ArrayOfPlot">
              <Plot Name="SMA" PlotColor="0, 0, 255" Width="1" PlotStyle="Line" PenStyle="Solid" />
            </Value>
          </TAParam>
          <TAParam Name="XmlLines" IsProperty="true">
            <Value xsi:type="ArrayOfLine" />
          </TAParam>
          <TAParam Name="FixedInputParameters" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">0</Value>
          </TAParam>
          <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
          <TAParam Name="AutoScale" IsProperty="true">
            <Value xsi:type="xsd:boolean">false</Value>
          </TAParam>
          <TAParam Name="InputPriceType" IsProperty="true">
            <Value xsi:type="xsd:unsignedByte">4</Value>
          </TAParam>
          <TAParam Name="CustomInput" IsProperty="true" />
          <TAParam Name="CalculateOnBarClose" IsProperty="true">
            <Value xsi:type="xsd:boolean">true</Value>
          </TAParam>
          <TAParam Name="BarsRequired" IsProperty="true">
            <Value xsi:type="xsd:int">20</Value>
          </TAParam>
          <TAParam Name="Caption" IsProperty="true">
            <Value xsi:type="xsd:string">SMA(Close, 14)</Value>
          </TAParam>
          <TAParam Name="Tags" IsProperty="true" />
        </Params>
      </XmlIndicator>
    </Lexems>
    <Lexems xsi:type="ScanLexemArifmeticOperation" Operation="Multiple" />
    <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="2" CharValue="0" />
    <Lexems xsi:type="ScanLexemEol" />
    <Lexems xsi:type="ScanLexemCloseBracket" />
    <IsAdvanced>true</IsAdvanced>
  </Lexems>
  <Lexems xsi:type="ScanLexemCloseBracket" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="MFI" Type="Indicator" FullTypeName="AgenaTrader.Custom.MFI">
      <Params>
        <TAParam Name="Period" IsProperty="true">
          <Value xsi:type="xsd:int">14</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">1 Day</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">New Panel</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="MFI" PlotColor="Blue" Width="1" PlotStyle="Line" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine">
            <Line Name="Lower" XmlColor="DarkViolet" Value="20" Width="1" DashStyle="Solid" />
            <Line Name="Upper" XmlColor="YellowGreen" Value="80" Width="1" DashStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">MFI(Close, 14)</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Less" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="35" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemSerie" Type="High">
    <TimeFrame>1 Day</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemSerie" Type="Low">
    <TimeFrame>1 Day</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="MarketPhasesPro" Type="Indicator" FullTypeName="AgenaTrader.Custom.MarketPhasesPro">
      <Params>
        <TAParam Name="TrendSize" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="Phase4Level" IsProperty="true">
          <Value xsi:type="xsd:double">0.2</Value>
        </TAParam>
        <TAParam Name="Phase5Level" IsProperty="true">
          <Value xsi:type="xsd:double">0.5</Value>
        </TAParam>
        <TAParam Name="P2ValidationMethod" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="P2Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3Distance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="P3BreakageDistance" IsProperty="true">
          <Value xsi:type="xsd:double">0</Value>
        </TAParam>
        <TAParam Name="BreakTheTrendByCS" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="Location" IsProperty="true">
          <Value xsi:type="xsd:int">1</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">1 Day</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot">
            <Plot Name="MarketPhase" PlotColor="DarkOrange" Width="4" PlotStyle="Bar" PenStyle="Solid" />
          </Value>
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">200</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">Market Phases Pro</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemIndicator" Serie="IsInsideBar" IsFloatPoint="true">
    <BarsAgo>0</BarsAgo>
    <XmlIndicator Name="InsideBarsMT" Type="Indicator" FullTypeName="AgenaTrader.Custom.InsideBarsMT">
      <Params>
        <TAParam Name="MarkerColorUpSerialize" IsProperty="true">
          <Value xsi:type="xsd:string">Yellow</Value>
        </TAParam>
        <TAParam Name="Opacity" IsProperty="true">
          <Value xsi:type="xsd:int">100</Value>
        </TAParam>
        <TAParam Name="ToleranceUnit" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="ToleranceValue" IsProperty="true">
          <Value xsi:type="xsd:double">2</Value>
        </TAParam>
        <TAParam Name="XmlInstrument" IsProperty="true" />
        <TAParam Name="TimeFrame" IsProperty="true">
          <Value xsi:type="xsd:string">1 Day</Value>
        </TAParam>
        <TAParam Name="VisibleIndicatorValues" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Overlay" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="DisplayInDataBox" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="PaintPriceMarkers" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="VerticalGridLines" IsProperty="true" />
        <TAParam Name="DrawOnPricePanel" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="Displacement" IsProperty="true">
          <Value xsi:type="xsd:int">0</Value>
        </TAParam>
        <TAParam Name="Panel" IsProperty="true">
          <Value xsi:type="xsd:string">Same as input series</Value>
        </TAParam>
        <TAParam Name="IsPanelCustom" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="XmlPlots" IsProperty="true">
          <Value xsi:type="ArrayOfPlot" />
        </TAParam>
        <TAParam Name="XmlLines" IsProperty="true">
          <Value xsi:type="ArrayOfLine" />
        </TAParam>
        <TAParam Name="FixedInputParameters" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">0</Value>
        </TAParam>
        <TAParam Name="ValuesDisplayStyle" IsProperty="true" />
        <TAParam Name="AutoScale" IsProperty="true">
          <Value xsi:type="xsd:boolean">false</Value>
        </TAParam>
        <TAParam Name="InputPriceType" IsProperty="true">
          <Value xsi:type="xsd:unsignedByte">3</Value>
        </TAParam>
        <TAParam Name="CustomInput" IsProperty="true" />
        <TAParam Name="CalculateOnBarClose" IsProperty="true">
          <Value xsi:type="xsd:boolean">true</Value>
        </TAParam>
        <TAParam Name="BarsRequired" IsProperty="true">
          <Value xsi:type="xsd:int">20</Value>
        </TAParam>
        <TAParam Name="Caption" IsProperty="true">
          <Value xsi:type="xsd:string">InsideBarsMT</Value>
        </TAParam>
        <TAParam Name="Tags" IsProperty="true" />
      </Params>
    </XmlIndicator>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Equal" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" CharValue="0" />
  <Lexems xsi:type="ScanLexemCondition" Condition="And" />
  <Lexems xsi:type="ScanLexemEol" />
  <Lexems xsi:type="ScanLexemSerie" Type="Close">
    <TimeFrame>1 Day</TimeFrame>
    <BarsAgo>0</BarsAgo>
  </Lexems>
  <Lexems xsi:type="ScanLexemOperation" Operation="Great" />
  <Lexems xsi:type="ScanLexemValue" LexemType="Double" Value="8" CharValue="0" />
  <Lexems xsi:type="ScanLexemEol" />
  <CalculateOnClosedBar xsi:nil="true" />
</ScanWizartState>
*/
#endregion
